# Generated by Django 2.2.7 on 2019-12-01 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='baslik',
            field=models.CharField(max_length=144, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='durum',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='eklenme_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Deadline'),
        ),
    ]
